### ISSUE TITLE
Required file typo

### ISSUE THREAD

**Issue by haldoh** [hanwencheng/CommonSubstrings#2]
Hello,

I was trying out the library, and noticed that there is a typo in index.js. [Here](https://github.com/hanwencheng/CommonSubstrings/blob/master/index.js#L1) it requires:

`var SuffixTrie= require('./lib/CommonSubstrings.min');`

But the file is named commonSubstrings.min (no capital C). You can also see it failing in the [runkit link](https://runkit.com/npm/common-substrings) provided in the npm page.

Bye, Aldo.

**Comment by hanwencheng** [comment]
Hi, Aldo,

Thanks a lot, I just fixed it.

Best, Hanwen
